services:
  # Gestores de Descargas (Torrent)
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    restart: unless-stopped
    volumes:
      - ${ARRPATH}qbittorrent/config:/config
      - ${ARRPATH}downloads:/downloads
    ports:
      - "8080:8080"       # Interfaz Web
      - "6881:6881"       # Puerto TCP para Torrents
      - "6881:6881/udp"   # Puerto UDP para Torrents
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    env_file:
      - ./.env

  # Indexadores
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    restart: unless-stopped
    volumes:
      - ${ARRPATH}prowlarr/config:/config
      - ${ARRPATH}prowlarr/backup:/data/backup
      - ${ARRPATH}downloads:/downloads
    ports:
      - "9696:9696"       # Interfaz Web
    env_file:
      - ./.env

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    hostname: jackett
    restart: unless-stopped
    volumes:
      - ${ARRPATH}jackett/data:/config
      - ${ARRPATH}blackhole:/downloads
    ports:
      - "9117:9117"       # Interfaz Web
    env_file:
      - ./.env

  # Gestión de Medios (Películas y Series)
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    restart: unless-stopped
    volumes:
      - ${ARRPATH}sonarr/config:/config
      - ${ARRPATH}sonarr/backup:/data/backup
      - ${ARRPATH}sonarr/tvshows:/data/tvshows
      - ${ARRPATH}downloads:/downloads
    ports:
      - "8989:8989"       # Interfaz Web
    env_file:
      - ./.env

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    restart: unless-stopped
    volumes:
      - ${ARRPATH}radarr/config:/config
      - ${ARRPATH}radarr/movies:/data/movies
      - ${ARRPATH}radarr/backup:/data/backup
      - ${ARRPATH}downloads:/downloads
    ports:
      - "7878:7878"       # Interfaz Web
    env_file:
      - ./.env

  # Servidores de Streaming Multimedia
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    restart: unless-stopped
    volumes:
      - ${ARRPATH}jellyfin/config:/config
      - ${ARRPATH}radarr/movies:/data/movies
      - ${ARRPATH}sonarr/tvshows:/data/tvshows
    ports:
      - "8096:8096/tcp"   # Interfaz Web
      - "7359:7359/udp"   # Descubrimiento automático
      - "1900:1900/udp"   # DLNA/UPnP
    env_file:
      - ./.env

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: plex
    network_mode: host #El puerto será 32400, entra en IP:32400/web
    restart: unless-stopped
    environment:
      - VERSION=docker
      # Si quieres que Plex se reclame automáticamente, descomenta y pon tu token:
      # - PLEX_CLAIM=<TU_PLEX_CLAIM_TOKEN>
    volumes:
      - ${ARRPATH}plex/config:/config
      - ${ARRPATH}sonarr/tvshows:/data/tvshows
      - ${ARRPATH}radarr/movies:/data/movies
    env_file:
      - ./.env